name: Checks

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' # 12:00 PT

jobs:

  # check upstream `PHP_DEFAULT_VERSION` every night
  # so we can bump the `deb base` version in `fpm.sh`
  debian-version:

    name: Check Debian PHP version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      PKG_DEFAULT_PHP_VERSION: '8.3'

    steps:

      - name: Check upstream PHP_DEFAULT_VERSION
        env:
          RULES_URL: https://salsa.debian.org/php-team/php-defaults/-/raw/main/debian/rules
        run: |
          RULES=$(curl -sSL $RULES_URL)
          VARIABLE_LINE=$(echo "$RULES" | grep '^PHP_DEFAULT_VERSION ')
          RAW_VERSION=${VARIABLE_LINE#*:=}
          PHP_DEFAULT_VERSION=${RAW_VERSION// /}

          echo "Remote default version: ${PHP_DEFAULT_VERSION}"
          echo "Package base version: ${PKG_DEFAULT_PHP_VERSION}"

          if [ "$PHP_DEFAULT_VERSION" != "$PKG_DEFAULT_PHP_VERSION" ]; then
            exit 1
          fi
