name: Build packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:

  build:

    name: Build packages
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the Docker image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/fpm:latest
          docker tag ghcr.io/${{ github.repository_owner }}/fpm:latest fpm

      - name: Bundle packages
        run: |
          cd build
          docker run --tty \
            -v ${PWD}:/root/build \
            fpm /bin/bash -c "./fpm.sh ${{ github.event.inputs.tag }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: build/dist/*
